### ISSUE TITLE
Bump to Quarkus 2.13

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#183]

**Comment by oliv37** [comment]
I'm getting the following error when executing test `VillainResourceTest.shouldNotAddInvalidItem()` with Quarkus **2.13.1** : 

```
2022-10-08 15:18:18,874 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /api/villains failed, error id: 76cb5d1d-ebcf-434f-b7ba-687a6ad797c5-1: java.lang.NullPointerException
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveViolationExceptionMapper.buildViolationReportResponse(ResteasyReactiveViolationExceptionMapper.java:78)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveViolationExceptionMapper.toResponse(ResteasyReactiveViolationExceptionMapper.java:43)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveViolationExceptionMapper.toResponse(ResteasyReactiveViolationExceptionMapper.java:24)
        at org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper.mapException(RuntimeExceptionMapper.java:95)
        at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.mapExceptionIfPresent(ResteasyReactiveRequestContext.java:342)
        at org.jboss.resteasy.reactive.server.handlers.ExceptionHandler.handle(ExceptionHandler.java:15)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:124)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:142)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Adding `@Produces(APPLICATION_JSON)` to `VillainResource.createVillain` solves the problem although I don't really understand why.

**Comment by cescoffier** [comment]
Hum that looks like a bug. @geoand  @gsmet any changes that could explain it?

**Comment by geoand** [comment]
Definitely sounds like a bug. Not sure what could have caused it

**Comment by gsmet** [comment]
Given changing the content type fixes the issue, maybe the PR that pushed plain text violation errors for plain text?

**Comment by geoand** [comment]
That seems very likely given the stactktrace, let me take a closer look.
