### ISSUE TITLE
Native build does not work for narration microservice

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus-workshops#405]
If we build everything at the top level with the `-Pnative` profile, we get the following failure in the narration microservice:

```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.channel.epoll.Native the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.epoll.Native' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'Native.class'). To see why io.netty.channel.epoll.Native got initialized use --trace-class-initialization=io.netty.channel.epoll.Native
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.handler.ssl.ReferenceCountedOpenSslContext the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with 'ReferenceCountedOpenSslContext.class'). To see why io.netty.handler.ssl.ReferenceCountedOpenSslContext got initialized use --trace-class-initialization=io.netty.handler.ssl.ReferenceCountedOpenSslContext
io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.UnpooledHeapByteBuf'). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.internal.tcnative.SSL the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.internal.tcnative.SSL'). To see why io.netty.internal.tcnative.SSL got initialized use --trace-class-initialization=io.netty.internal.tcnative.SSL
io.netty.buffer.AbstractPooledDerivedByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.AbstractPooledDerivedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractPooledDerivedByteBuf
io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.UnpooledDirectByteBuf'). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
io.netty.handler.ssl.OpenSslContext the class was requested to be initialized at run time (subtype of io.netty.handler.ssl.ReferenceCountedOpenSslContext). To see why io.netty.handler.ssl.OpenSslContext got initialized use --trace-class-initialization=io.netty.handler.ssl.OpenSslContext
io.netty.handler.ssl.ReferenceCountedOpenSslClientContext the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.handler.ssl.ReferenceCountedOpenSslClientContext' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ReferenceCountedOpenSslClientContext.class' and subtype of io.netty.handler.ssl.ReferenceCountedOpenSslContext). To see why io.netty.handler.ssl.ReferenceCountedOpenSslClientContext got initialized use --trace-class-initialization=io.netty.handler.ssl.ReferenceCountedOpenSslClientContext
io.netty.channel.epoll.LinuxSocket the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.epoll.LinuxSocket' and subtype of io.netty.channel.unix.Socket and subtype of io.netty.channel.unix.FileDescriptor). To see why io.netty.channel.epoll.LinuxSocket got initialized use --trace-class-initialization=io.netty.channel.epoll.LinuxSocket
io.netty.buffer.PooledByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledByteBuf got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBuf
io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and subtype of io.netty.buffer.UnpooledDirectByteBuf and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.UnpooledUnsafeDirectByteBuf'). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
io.netty.internal.tcnative.CertificateVerifier the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.internal.tcnative.CertificateVerifier'). To see why io.netty.internal.tcnative.CertificateVerifier got initialized use --trace-class-initialization=io.netty.internal.tcnative.CertificateVerifier
io.netty.handler.ssl.OpenSsl the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.handler.ssl.OpenSsl'). To see why io.netty.handler.ssl.OpenSsl got initialized use --trace-class-initialization=io.netty.handler.ssl.OpenSsl
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.util.AbstractReferenceCounted' and from 'META-INF/native-image/io.netty/netty-common/native-image.properties' in 'file:///project/lib/io.netty.netty-common-4.1.97.Final.jar' with 'io.netty.util.AbstractReferenceCounted'). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted
io.netty.buffer.PooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.PooledUnsafeDirectByteBuf
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and subtype of io.netty.buffer.UnpooledDirectByteBuf and subtype of io.netty.buffer.UnpooledUnsafeDirectByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
io.netty.handler.ssl.OpenSslClientContext the class was requested to be initialized at run time (subtype of io.netty.handler.ssl.ReferenceCountedOpenSslContext). To see why io.netty.handler.ssl.OpenSslClientContext got initialized use --trace-class-initialization=io.netty.handler.ssl.OpenSslClientContext
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf' and from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
io.netty.channel.epoll.Epoll the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.epoll.Epoll' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'Epoll.class'). To see why io.netty.channel.epoll.Epoll got initialized use --trace-class-initialization=io.netty.channel.epoll.Epoll
io.netty.handler.ssl.PemValue the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted). To see why io.netty.handler.ssl.PemValue got initialized use --trace-class-initialization=io.netty.handler.ssl.PemValue
io.netty.channel.DefaultFileRegion the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted). To see why io.netty.channel.DefaultFileRegion got initialized use --trace-class-initialization=io.netty.channel.DefaultFileRegion
io.netty.buffer.PooledSlicedByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledSlicedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.PooledSlicedByteBuf
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.channel.unix.Socket the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.unix.Socket' and subtype of io.netty.channel.unix.FileDescriptor). To see why io.netty.channel.unix.Socket got initialized use --trace-class-initialization=io.netty.channel.unix.Socket
io.netty.channel.unix.FileDescriptor the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with 'FileDescriptor.class'). To see why io.netty.channel.unix.FileDescriptor got initialized use --trace-class-initialization=io.netty.channel.unix.FileDescriptor
io.netty.handler.ssl.PemPrivateKey the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted). To see why io.netty.handler.ssl.PemPrivateKey got initialized use --trace-class-initialization=io.netty.handler.ssl.PemPrivateKey
To see how the classes got initialized, use --trace-class-initialization=io.netty.channel.epoll.Native,io.netty.buffer.ByteBufUtil,io.netty.handler.ssl.ReferenceCountedOpenSslContext,io.netty.buffer.UnpooledHeapByteBuf,io.netty.internal.tcnative.SSL,io.netty.buffer.AbstractPooledDerivedByteBuf,io.netty.buffer.UnpooledDirectByteBuf,io.netty.handler.ssl.OpenSslContext,io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,io.netty.channel.epoll.LinuxSocket,io.netty.buffer.PooledByteBuf,io.netty.buffer.UnpooledUnsafeDirectByteBuf,io.netty.internal.tcnative.CertificateVerifier,io.netty.handler.ssl.OpenSsl,io.netty.util.AbstractReferenceCounted,io.netty.buffer.PooledUnsafeDirectByteBuf,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf,io.netty.handler.ssl.OpenSslClientContext,io.netty.buffer.AbstractReferenceCountedByteBuf,io.netty.channel.epoll.Epoll,io.netty.handler.ssl.PemValue,io.netty.channel.DefaultFileRegion,io.netty.buffer.PooledSlicedByteBuf,io.netty.buffer.ByteBufAllocator,io.netty.channel.unix.Socket,io.netty.channel.unix.FileDescriptor,io.netty.handler.ssl.PemPrivateKey
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.channel.epoll.Native the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.epoll.Native' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'Native.class'). To see why io.netty.channel.epoll.Native got initialized use --trace-class-initialization=io.netty.channel.epoll.Native
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.handler.ssl.ReferenceCountedOpenSslContext the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with 'ReferenceCountedOpenSslContext.class'). To see why io.netty.handler.ssl.ReferenceCountedOpenSslContext got initialized use --trace-class-initialization=io.netty.handler.ssl.ReferenceCountedOpenSslContext
io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.UnpooledHeapByteBuf'). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.internal.tcnative.SSL the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.internal.tcnative.SSL'). To see why io.netty.internal.tcnative.SSL got initialized use --trace-class-initialization=io.netty.internal.tcnative.SSL
io.netty.buffer.AbstractPooledDerivedByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.AbstractPooledDerivedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractPooledDerivedByteBuf
io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.UnpooledDirectByteBuf'). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
io.netty.handler.ssl.OpenSslContext the class was requested to be initialized at run time (subtype of io.netty.handler.ssl.ReferenceCountedOpenSslContext). To see why io.netty.handler.ssl.OpenSslContext got initialized use --trace-class-initialization=io.netty.handler.ssl.OpenSslContext
io.netty.handler.ssl.ReferenceCountedOpenSslClientContext the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.handler.ssl.ReferenceCountedOpenSslClientContext' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ReferenceCountedOpenSslClientContext.class' and subtype of io.netty.handler.ssl.ReferenceCountedOpenSslContext). To see why io.netty.handler.ssl.ReferenceCountedOpenSslClientContext got initialized use --trace-class-initialization=io.netty.handler.ssl.ReferenceCountedOpenSslClientContext
io.netty.channel.epoll.LinuxSocket the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.epoll.LinuxSocket' and subtype of io.netty.channel.unix.Socket and subtype of io.netty.channel.unix.FileDescriptor). To see why io.netty.channel.epoll.LinuxSocket got initialized use --trace-class-initialization=io.netty.channel.epoll.LinuxSocket
io.netty.buffer.PooledByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledByteBuf got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBuf
io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and subtype of io.netty.buffer.UnpooledDirectByteBuf and from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.UnpooledUnsafeDirectByteBuf'). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
io.netty.internal.tcnative.CertificateVerifier the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.internal.tcnative.CertificateVerifier'). To see why io.netty.internal.tcnative.CertificateVerifier got initialized use --trace-class-initialization=io.netty.internal.tcnative.CertificateVerifier
io.netty.handler.ssl.OpenSsl the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.handler.ssl.OpenSsl'). To see why io.netty.handler.ssl.OpenSsl got initialized use --trace-class-initialization=io.netty.handler.ssl.OpenSsl
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.util.AbstractReferenceCounted' and from 'META-INF/native-image/io.netty/netty-common/native-image.properties' in 'file:///project/lib/io.netty.netty-common-4.1.97.Final.jar' with 'io.netty.util.AbstractReferenceCounted'). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted
io.netty.buffer.PooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.PooledUnsafeDirectByteBuf
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf and subtype of io.netty.buffer.UnpooledDirectByteBuf and subtype of io.netty.buffer.UnpooledUnsafeDirectByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
io.netty.handler.ssl.OpenSslClientContext the class was requested to be initialized at run time (subtype of io.netty.handler.ssl.ReferenceCountedOpenSslContext). To see why io.netty.handler.ssl.OpenSslClientContext got initialized use --trace-class-initialization=io.netty.handler.ssl.OpenSslClientContext
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf' and from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
io.netty.channel.epoll.Epoll the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.epoll.Epoll' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'Epoll.class'). To see why io.netty.channel.epoll.Epoll got initialized use --trace-class-initialization=io.netty.channel.epoll.Epoll
io.netty.handler.ssl.PemValue the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted). To see why io.netty.handler.ssl.PemValue got initialized use --trace-class-initialization=io.netty.handler.ssl.PemValue
io.netty.channel.DefaultFileRegion the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted). To see why io.netty.channel.DefaultFileRegion got initialized use --trace-class-initialization=io.netty.channel.DefaultFileRegion
io.netty.buffer.PooledSlicedByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledSlicedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.PooledSlicedByteBuf
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.97.Final.jar' with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.channel.unix.Socket the class was requested to be initialized at run time (from 'META-INF/native-image/com.azure/azure-core-http-netty/native-image.properties' in 'file:///project/lib/com.azure.azure-core-http-netty-1.13.2.jar' with 'io.netty.channel.unix.Socket' and subtype of io.netty.channel.unix.FileDescriptor). To see why io.netty.channel.unix.Socket got initialized use --trace-class-initialization=io.netty.channel.unix.Socket
io.netty.channel.unix.FileDescriptor the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with 'FileDescriptor.class'). To see why io.netty.channel.unix.FileDescriptor got initialized use --trace-class-initialization=io.netty.channel.unix.FileDescriptor
io.netty.handler.ssl.PemPrivateKey the class was requested to be initialized at run time (subtype of io.netty.util.AbstractReferenceCounted). To see why io.netty.handler.ssl.PemPrivateKey got initialized use --trace-class-initialization=io.netty.handler.ssl.PemPrivateKey
To see how the classes got initialized, use --trace-class-initialization=io.netty.channel.epoll.Native,io.netty.buffer.ByteBufUtil,io.netty.handler.ssl.ReferenceCountedOpenSslContext,io.netty.buffer.UnpooledHeapByteBuf,io.netty.internal.tcnative.SSL,io.netty.buffer.AbstractPooledDerivedByteBuf,io.netty.buffer.UnpooledDirectByteBuf,io.netty.handler.ssl.OpenSslContext,io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,io.netty.channel.epoll.LinuxSocket,io.netty.buffer.PooledByteBuf,io.netty.buffer.UnpooledUnsafeDirectByteBuf,io.netty.internal.tcnative.CertificateVerifier,io.netty.handler.ssl.OpenSsl,io.netty.util.AbstractReferenceCounted,io.netty.buffer.PooledUnsafeDirectByteBuf,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf,io.netty.handler.ssl.OpenSslClientContext,io.netty.buffer.AbstractReferenceCountedByteBuf,io.netty.channel.epoll.Epoll,io.netty.handler.ssl.PemValue,io.netty.channel.DefaultFileRegion,io.netty.buffer.PooledSlicedByteBuf,io.netty.buffer.ByteBufAllocator,io.netty.channel.unix.Socket,io.netty.channel.unix.FileDescriptor,io.netty.handler.ssl.PemPrivateKey
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:277)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:164)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:770)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:770)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:179)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
------------------------------------------------------------------------------------------------------------------------
                       21.8s (12.6% of total time) in 62 GCs | Peak RSS: 2.60GB | CPU load: 1.94
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/rest-narration-1.0.0-SNAPSHOT-runner-build-output-stats.json (build_info)
========================================================================================================================
Finished generating 'rest-narration-1.0.0-SNAPSHOT-runner' in 2m 51s.
```

To work around the problem I've set the CI build to only build the core with native (which is what we used to do before #233. As part of the fix for this we should re-enable the native build for all modules (but we may also need #404).

**Comment by holly-cummins** [comment]
I think it will be some time before semantic kernel works with native, but we should make sure that the user experience here is ok. In the CI build I explicitly exclude the narration service, but it would be better to handle it gracefully in the pom so that if people do a top-level native build locally, things still work.
